### ISSUE TITLE
Charts by the dashboard site

### ISSUE THREAD

**Issue by nikhil** [mskcc/Voyager-Operation-Dashboard#4]
A dashboard page that can show some quick statistics that CAS needs:

- An example would include genepanel distribution across the beagle database
- Distributions of RUNs by status - Completed, Failed, Pending

**Comment by nikhil** [comment]
v1 Mockup of the dashboard site
![dashboard_page](https://user-images.githubusercontent.com/4000697/193920149-0e54cd3f-8eef-431d-8772-339475dcf812.png)

**Comment by nikhil** [comment]
To get the Fastq distribution use this api call, http://localhost:8081/v0/fs/files/?values_metadata=genePanel
note values_metadata is set to `genePanel`
The run status can be retrieved from this api call, http://voyager:5001/v0/run/api/?run_distribution=status.
Note that the keys here are numbers representing the beagle status objects. We are working to fix this, but in the meantime you can use the status mapping found here: https://github.com/mskcc/beagle/blob/master/runner/models.py#L18

**Comment by RaccoonNW** [comment]
Found this library for a nice spread of chart options:

https://www.react-google-charts.com/examples/pie-chart

**Comment by nikhil** [comment]
https://www.chartjs.org/

**Comment by nikhil** [comment]
The updated genePanel endpoint is here: http://localhost:8081/v0/fs/distribution/?metadata_distribution=genePanel

```
{
  "IMPACT505": 16910,
  "ShallowWGS": 18308,
  "CMO-CH": 8308,
  "HumanWholeGenome": 11374,
  "ACCESS": 10618,
  "WholeExome": 35652
}
```
